<?php

namespace App\Service\DataInitializer;

class Data
{
    private $client = [
        'name' => 'AH-CHOU',
        'email' => 'planetair974@gmail.com',
        'phone' => '+262 692 61 92 04',
        'color' => '#d32f2f',
        'active' => true,
        'timezone' => 'Indian/Reunion',
        'address' => '9 allée des champignons',
        'zipcode' => '97450',
        'city' => 'Saint-Louis',
        'website' => 'https://www.planetair974.fr',
        'url' => 'https://ah-chou.creazot.com',
        'harelUrl' => 'https://demoahchou.creazot.io',
        'emailAddressSender' => 'contact@planetair974.com',
        "rateEditable" => false, 
        "convertedPriceEditable" => false,
        "dateRateName" => "Date",
        "itemsPartName" => "Produits",
        "taxesPartName" => "Autres coûts",
        "costPricesPartName" => "Prix de revient"
    ];

    private $currencies = [
        ["code" => "AED", "devise" => "Dirham des Émirats arabes unis", "pays" => "Émirats arabes unis"],
        ["code" => "AFN", "devise" => "Afghani afghan", "pays" => "Afghanistan"],
        ["code" => "ALL", "devise" => "Lek albanais", "pays" => "Albanie"],
        ["code" => "AMD", "devise" => "Dram arménien", "pays" => "Arménie"],
        ["code" => "ANG", "devise" => "Florin antillais néerlandais", "pays" => "Antilles néerlandaises"],
        ["code" => "AOA", "devise" => "Kwanza angolais", "pays" => "Angola"],
        ["code" => "ARS", "devise" => "Peso argentin", "pays" => "Argentine"],
        ["code" => "AUD", "devise" => "Dollar australien", "pays" => "Australie"],
        ["code" => "AWG", "devise" => "Florin arubais", "pays" => "Aruba"],
        ["code" => "AZN", "devise" => "Manat azerbaïdjanais", "pays" => "Azerbaïdjan"],
        ["code" => "BAM", "devise" => "Mark convertible de Bosnie-Herzégovine", "pays" => "Bosnie-Herzégovine"],
        ["code" => "BBD", "devise" => "Dollar barbadien", "pays" => "Barbade"],
        ["code" => "BDT", "devise" => "Taka bangladais", "pays" => "Bangladesh"],
        ["code" => "BGN", "devise" => "Lev bulgare", "pays" => "Bulgarie"],
        ["code" => "BHD", "devise" => "Dinar bahreïni", "pays" => "Bahreïn"],
        ["code" => "BIF", "devise" => "Franc burundais", "pays" => "Burundi"],
        ["code" => "BMD", "devise" => "Dollar bermudien", "pays" => "Bermudes"],
        ["code" => "BND", "devise" => "Dollar de Brunei", "pays" => "Brunei"],
        ["code" => "BOB", "devise" => "Boliviano bolivien", "pays" => "Bolivie"],
        ["code" => "BRL", "devise" => "Réal brésilien", "pays" => "Brésil"],
        ["code" => "BSD", "devise" => "Dollar bahaméen", "pays" => "Bahamas"],
        ["code" => "BTN", "devise" => "Ngultrum bhoutanais", "pays" => "Bhoutan"],
        ["code" => "BWP", "devise" => "Pula botswanais", "pays" => "Botswana"],
        ["code" => "BYN", "devise" => "Rouble biélorusse", "pays" => "Biélorussie"],
        ["code" => "BZD", "devise" => "Dollar bélizéen", "pays" => "Belize"],
        ["code" => "CAD", "devise" => "Dollar canadien", "pays" => "Canada"],
        ["code" => "CDF", "devise" => "Franc congolais", "pays" => "République démocratique du Congo"],
        ["code" => "CHF", "devise" => "Franc suisse", "pays" => "Suisse"],
        ["code" => "CLP", "devise" => "Peso chilien", "pays" => "Chili"],
        ["code" => "CNY", "devise" => "Yuan renminbi chinois", "pays" => "Chine"],
        ["code" => "COP", "devise" => "Peso colombien", "pays" => "Colombie"],
        ["code" => "CRC", "devise" => "Colon costaricain", "pays" => "Costa Rica"],
        ["code" => "CUP", "devise" => "Peso cubain", "pays" => "Cuba"],
        ["code" => "CVE", "devise" => "Escudo cap-verdien", "pays" => "Cap-Vert"],
        ["code" => "CZK", "devise" => "Couronne tchèque", "pays" => "République tchèque"],
        ["code" => "DJF", "devise" => "Franc djiboutien", "pays" => "Djibouti"],
        ["code" => "DKK", "devise" => "Couronne danoise", "pays" => "Danemark"],
        ["code" => "DOP", "devise" => "Peso dominicain", "pays" => "République dominicaine"],
        ["code" => "DZD", "devise" => "Dinar algérien", "pays" => "Algérie"],
        ["code" => "EGP", "devise" => "Livre égyptienne", "pays" => "Égypte"],
        ["code" => "ERN", "devise" => "Nakfa érythréen", "pays" => "Érythrée"],
        ["code" => "ETB", "devise" => "Birr éthiopien", "pays" => "Éthiopie"],
        ["code" => "EUR", "devise" => "Euro", "pays" => "Union européenne"],
        ["code" => "FJD", "devise" => "Dollar fidjien", "pays" => "Fidji"],
        ["code" => "GBP", "devise" => "Livre sterling", "pays" => "Royaume-Uni"],
        ["code" => "GEL", "devise" => "Lari géorgien", "pays" => "Géorgie"],
        ["code" => "GHS", "devise" => "Cedi ghanéen", "pays" => "Ghana"],
        ["code" => "GNF", "devise" => "Franc guinéen", "pays" => "Guinée"],
        ["code" => "HKD", "devise" => "Dollar de Hong Kong", "pays" => "Hong Kong"],
        ["code" => "HRK", "devise" => "Kuna croate", "pays" => "Croatie"],
        ["code" => "HUF", "devise" => "Forint hongrois", "pays" => "Hongrie"],
        ["code" => "IDR", "devise" => "Roupie indonésienne", "pays" => "Indonésie"],
        ["code" => "ILS", "devise" => "Nouveau shekel israélien", "pays" => "Israël"],
        ["code" => "INR", "devise" => "Roupie indienne", "pays" => "Inde"],
        ["code" => "IQD", "devise" => "Dinar irakien", "pays" => "Irak"],
        ["code" => "IRR", "devise" => "Rial iranien", "pays" => "Iran"],
        ["code" => "ISK", "devise" => "Couronne islandaise", "pays" => "Islande"],
        ["code" => "JPY", "devise" => "Yen japonais", "pays" => "Japon"],
        ["code" => "KES", "devise" => "Shilling kényan", "pays" => "Kenya"],
        ["code" => "KRW", "devise" => "Won sud-coréen", "pays" => "Corée du Sud"],
        ["code" => "KWD", "devise" => "Dinar koweïtien", "pays" => "Koweït"],
        ["code" => "KZT", "devise" => "Tenge kazakh", "pays" => "Kazakhstan"],
        ["code" => "LBP", "devise" => "Livre libanaise", "pays" => "Liban"],
        ["code" => "LKR", "devise" => "Roupie srilankaise", "pays" => "Sri Lanka"],
        ["code" => "MAD", "devise" => "Dirham marocain", "pays" => "Maroc"],
        ["code" => "MGA", "devise" => "Ariary malgache", "pays" => "Madagascar"],
        ["code" => "MRU", "devise" => "Ouguiya mauritanienne", "pays" => "Mauritanie"],
        ["code" => "MUR", "devise" => "Roupie mauricienne", "pays" => "Maurice"],
        ["code" => "MXN", "devise" => "Peso mexicain", "pays" => "Mexique"],
        ["code" => "MYR", "devise" => "Ringgit malaisien", "pays" => "Malaisie"],
        ["code" => "NAD", "devise" => "Dollar namibien", "pays" => "Namibie"],
        ["code" => "NGN", "devise" => "Naira nigérian", "pays" => "Nigéria"],
        ["code" => "NOK", "devise" => "Couronne norvégienne", "pays" => "Norvège"],
        ["code" => "NZD", "devise" => "Dollar néo-zélandais", "pays" => "Nouvelle-Zélande"],
        ["code" => "OMR", "devise" => "Rial omanais", "pays" => "Oman"],
        ["code" => "PEN", "devise" => "Sol péruvien", "pays" => "Pérou"],
        ["code" => "PHP", "devise" => "Peso philippin", "pays" => "Philippines"],
        ["code" => "PKR", "devise" => "Roupie pakistanaise", "pays" => "Pakistan"],
        ["code" => "PLN", "devise" => "Zloty polonais", "pays" => "Pologne"],
        ["code" => "QAR", "devise" => "Riyal qatari", "pays" => "Qatar"],
        ["code" => "RON", "devise" => "Leu roumain", "pays" => "Roumanie"],
        ["code" => "RUB", "devise" => "Rouble russe", "pays" => "Russie"],
        ["code" => "SAR", "devise" => "Riyal saoudien", "pays" => "Arabie saoudite"],
        ["code" => "SEK", "devise" => "Couronne suédoise", "pays" => "Suède"],
        ["code" => "SGD", "devise" => "Dollar de Singapour", "pays" => "Singapour"],
        ["code" => "THB", "devise" => "Baht thaïlandais", "pays" => "Thaïlande"],
        ["code" => "TRY", "devise" => "Livre turque", "pays" => "Turquie"],
        ["code" => "TND", "devise" => "Dinar tunisien", "pays" => "Tunisie"],
        ["code" => "USD", "devise" => "Dollar américain", "pays" => "États-Unis"],
        ["code" => "XAF", "devise" => "Franc CFA d’Afrique centrale", "pays" => "CEMAC"],
        ["code" => "XOF", "devise" => "Franc CFA d’Afrique de l’Ouest", "pays" => "UEMOA"],
        ["code" => "XPF", "devise" => "Franc CFP", "pays" => "Collectivités d’outre-mer françaises"],
        ["code" => "ZAR", "devise" => "Rand sud-africain", "pays" => "Afrique du Sud"],
        ["code" => "FKP", "devise" => "Livre des îles Malouines", "pays" => "Îles Malouines"],
        ["code" => "FOK", "devise" => "Couronne féroïenne", "pays" => "Îles Féroé"],
        ["code" => "GGP", "devise" => "Livre de Guernesey", "pays" => "Guernesey"],
        ["code" => "GIP", "devise" => "Livre de Gibraltar", "pays" => "Gibraltar"],
        ["code" => "GMD", "devise" => "Dalasi gambien", "pays" => "Gambie"],
        ["code" => "GTQ", "devise" => "Quetzal guatémaltèque", "pays" => "Guatemala"],
        ["code" => "GYD", "devise" => "Dollar du Guyana", "pays" => "Guyana"],
        ["code" => "HNL", "devise" => "Lempira hondurien", "pays" => "Honduras"],
        ["code" => "HTG", "devise" => "Gourde haïtienne", "pays" => "Haïti"],
        ["code" => "IMP", "devise" => "Livre de Man", "pays" => "Île de Man"],
        ["code" => "JEP", "devise" => "Livre de Jersey", "pays" => "Jersey"],
        ["code" => "JMD", "devise" => "Dollar jamaïcain", "pays" => "Jamaïque"],
        ["code" => "JOD", "devise" => "Dinar jordanien", "pays" => "Jordanie"],
        ["code" => "KGS", "devise" => "Som kirghize", "pays" => "Kirghizistan"],
        ["code" => "KHR", "devise" => "Riel cambodgien", "pays" => "Cambodge"],
        ["code" => "KID", "devise" => "Dollar kiribatien", "pays" => "Kiribati"],
        ["code" => "KMF", "devise" => "Franc comorien", "pays" => "Comores"],
        ["code" => "KYD", "devise" => "Dollar des îles Caïmans", "pays" => "Îles Caïmans"],
        ["code" => "LAK", "devise" => "Kip laotien", "pays" => "Laos"],
        ["code" => "LRD", "devise" => "Dollar libérien", "pays" => "Libéria"],
        ["code" => "LSL", "devise" => "Loti lesothan", "pays" => "Lesotho"],
        ["code" => "LYD", "devise" => "Dinar libyen", "pays" => "Libye"],
        ["code" => "MDL", "devise" => "Leu moldave", "pays" => "Moldavie"],
        ["code" => "MKD", "devise" => "Denar macédonien", "pays" => "Macédoine du Nord"],
        ["code" => "MMK", "devise" => "Kyat birman", "pays" => "Myanmar"],
        ["code" => "MNT", "devise" => "Tögrög mongol", "pays" => "Mongolie"],
        ["code" => "MOP", "devise" => "Pataca macanaise", "pays" => "Macao"],
        ["code" => "MVR", "devise" => "Rufiyaa maldivienne", "pays" => "Maldives"],
        ["code" => "MWK", "devise" => "Kwacha malawite", "pays" => "Malawi"],
        ["code" => "MZN", "devise" => "Metical mozambicain", "pays" => "Mozambique"],
        ["code" => "NIO", "devise" => "Córdoba nicaraguayen", "pays" => "Nicaragua"],
        ["code" => "NPR", "devise" => "Roupie népalaise", "pays" => "Népal"],
        ["code" => "PAB", "devise" => "Balboa panaméen", "pays" => "Panama"],
        ["code" => "PGK", "devise" => "Kina papou-néo-guinéen", "pays" => "Papouasie-Nouvelle-Guinée"],
        ["code" => "PYG", "devise" => "Guarani paraguayen", "pays" => "Paraguay"],
        ["code" => "RSD", "devise" => "Dinar serbe", "pays" => "Serbie"],
        ["code" => "RWF", "devise" => "Franc rwandais", "pays" => "Rwanda"],
        ["code" => "SBD", "devise" => "Dollar des îles Salomon", "pays" => "Îles Salomon"],
        ["code" => "SCR", "devise" => "Roupie seychelloise", "pays" => "Seychelles"],
        ["code" => "SDG", "devise" => "Livre soudanaise", "pays" => "Soudan"],
        ["code" => "SHP", "devise" => "Livre de Sainte-Hélène", "pays" => "Sainte-Hélène"],
        ["code" => "SLE", "devise" => "Leone sierra-léonais", "pays" => "Sierra Leone"],
        ["code" => "SOS", "devise" => "Shilling somalien", "pays" => "Somalie"],
        ["code" => "SRD", "devise" => "Dollar surinamais", "pays" => "Suriname"],
        ["code" => "SSP", "devise" => "Livre sud-soudanaise", "pays" => "Soudan du Sud"],
        ["code" => "STN", "devise" => "Dobra de São Tomé-et-Príncipe", "pays" => "São Tomé-et-Príncipe"],
        ["code" => "SYP", "devise" => "Livre syrienne", "pays" => "Syrie"],
        ["code" => "SZL", "devise" => "Lilangeni eswatinien", "pays" => "Eswatini"],
        ["code" => "TJS", "devise" => "Somoni tadjik", "pays" => "Tadjikistan"],
        ["code" => "TMT", "devise" => "Manat turkmène", "pays" => "Turkménistan"],
        ["code" => "TOP", "devise" => "Pa'anga tongien", "pays" => "Tonga"],
        ["code" => "TTD", "devise" => "Dollar trinidadien", "pays" => "Trinité-et-Tobago"],
        ["code" => "TVD", "devise" => "Dollar tuvaluan", "pays" => "Tuvalu"],
        ["code" => "TWD", "devise" => "Nouveau dollar taïwanais", "pays" => "Taïwan"],
        ["code" => "TZS", "devise" => "Shilling tanzanien", "pays" => "Tanzanie"],
        ["code" => "UAH", "devise" => "Hryvnia ukrainienne", "pays" => "Ukraine"],
        ["code" => "UGX", "devise" => "Shilling ougandais", "pays" => "Ouganda"],
        ["code" => "UYU", "devise" => "Peso uruguayen", "pays" => "Uruguay"],
        ["code" => "UZS", "devise" => "Som ouzbek", "pays" => "Ouzbékistan"],
        ["code" => "VES", "devise" => "Bolívar souverain vénézuélien", "pays" => "Venezuela"],
        ["code" => "VND", "devise" => "Đồng vietnamien", "pays" => "Viêt Nam"],
        ["code" => "VUV", "devise" => "Vatu vanuatais", "pays" => "Vanuatu"],
        ["code" => "WST", "devise" => "Tālā samoan", "pays" => "Samoa"],
        ["code" => "XCD", "devise" => "Dollar des Caraïbes orientales", "pays" => "Organisation des États des Caraïbes orientales"],
        ["code" => "XDR", "devise" => "Droits de tirage spéciaux", "pays" => "Fonds monétaire international"],
        ["code" => "YER", "devise" => "Rial yéménite", "pays" => "Yémen"],
        ["code" => "ZMW", "devise" => "Kwacha zambien", "pays" => "Zambie"],
        ["code" => "ZWL", "devise" => "Dollar zimbabwéen", "pays" => "Zimbabwe"]
    ];

    private $types = [
        ["code" => "DD", "label" => "Droits de douane"],
        ["code" => "TVA", "label" => "TVA"],
        ["code" => "AT", "label" => "Autres taxes"]
    ];

    public function getClient()
    {
        return $this->client;
    }

    public function getCurrencies()
    {
        return $this->currencies;
    }

    public function getTaxTypes()
    {
        return $this->types;
    }
}