<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250819183645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE certificat_medical (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(100) DEFAULT NULL, medecin VARCHAR(150) DEFAULT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, validity_duration_months INT DEFAULT NULL, remarques TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, profil_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3C705FDB275ED078 ON certificat_medical (profil_id)');
        $this->addSql('ALTER TABLE certificat_medical ADD CONSTRAINT FK_3C705FDB275ED078 FOREIGN KEY (profil_id) REFERENCES profil_pilote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE certificat_medical DROP CONSTRAINT FK_3C705FDB275ED078');
        $this->addSql('DROP TABLE certificat_medical');
    }
}
