<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251016164509 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category_tax (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id INT DEFAULT NULL, tax_ids JSON DEFAULT NULL, achat_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB43172CFE95D117 ON category_tax (achat_id)');
        $this->addSql('CREATE TABLE category_tax_tax (category_tax_id INT NOT NULL, tax_id INT NOT NULL, PRIMARY KEY(category_tax_id, tax_id))');
        $this->addSql('CREATE INDEX IDX_AA376059BD40EEA3 ON category_tax_tax (category_tax_id)');
        $this->addSql('CREATE INDEX IDX_AA376059B2A824D8 ON category_tax_tax (tax_id)');
        $this->addSql('ALTER TABLE category_tax ADD CONSTRAINT FK_AB43172CFE95D117 FOREIGN KEY (achat_id) REFERENCES achat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category_tax_tax ADD CONSTRAINT FK_AA376059BD40EEA3 FOREIGN KEY (category_tax_id) REFERENCES category_tax (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category_tax_tax ADD CONSTRAINT FK_AA376059B2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE category_tax DROP CONSTRAINT FK_AB43172CFE95D117');
        $this->addSql('ALTER TABLE category_tax_tax DROP CONSTRAINT FK_AA376059BD40EEA3');
        $this->addSql('ALTER TABLE category_tax_tax DROP CONSTRAINT FK_AA376059B2A824D8');
        $this->addSql('DROP TABLE category_tax');
        $this->addSql('DROP TABLE category_tax_tax');
    }
}
