<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241101170629 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duree TIME(0) WITHOUT TIME ZONE DEFAULT NULL, aeronef_id INT DEFAULT NULL, pilote_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_51C88FADBCB14BD8 ON prestation (aeronef_id)');
        $this->addSql('CREATE INDEX IDX_51C88FADF510AAE9 ON prestation (pilote_id)');
        $this->addSql('ALTER TABLE prestation ADD CONSTRAINT FK_51C88FADBCB14BD8 FOREIGN KEY (aeronef_id) REFERENCES aeronef (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestation ADD CONSTRAINT FK_51C88FADF510AAE9 FOREIGN KEY (pilote_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vol ADD prestation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE vol ADD CONSTRAINT FK_95C97EB9E45C554 FOREIGN KEY (prestation_id) REFERENCES prestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_95C97EB9E45C554 ON vol (prestation_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE prestation DROP CONSTRAINT FK_51C88FADBCB14BD8');
        $this->addSql('ALTER TABLE prestation DROP CONSTRAINT FK_51C88FADF510AAE9');
        $this->addSql('DROP TABLE prestation');
        $this->addSql('ALTER TABLE vol DROP CONSTRAINT FK_95C97EB9E45C554');
        $this->addSql('DROP INDEX IDX_95C97EB9E45C554');
        $this->addSql('ALTER TABLE vol DROP prestation_id');
    }
}
