<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251027132916 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE other_cost (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, is_fix BOOLEAN DEFAULT NULL, currency VARCHAR(12) DEFAULT NULL, value DOUBLE PRECISION DEFAULT NULL, achat_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7162C22EFE95D117 ON other_cost (achat_id)');
        $this->addSql('ALTER TABLE other_cost ADD CONSTRAINT FK_7162C22EFE95D117 FOREIGN KEY (achat_id) REFERENCES achat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE achat ADD comment TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE achat ADD covering_exchange_rate DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE achat ADD covering_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE achat ADD total_covering_ht DOUBLE PRECISION DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE other_cost DROP CONSTRAINT FK_7162C22EFE95D117');
        $this->addSql('DROP TABLE other_cost');
        $this->addSql('ALTER TABLE achat DROP comment');
        $this->addSql('ALTER TABLE achat DROP covering_exchange_rate');
        $this->addSql('ALTER TABLE achat DROP covering_date');
        $this->addSql('ALTER TABLE achat DROP total_covering_ht');
    }
}
