<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250428075531 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE profil_pilote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_eleve BOOLEAN DEFAULT NULL, is_pro BOOLEAN DEFAULT NULL, is_instructeur BOOLEAN DEFAULT NULL, pilote_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1BCDDD8FF510AAE9 ON profil_pilote (pilote_id)');
        $this->addSql('ALTER TABLE profil_pilote ADD CONSTRAINT FK_1BCDDD8FF510AAE9 FOREIGN KEY (pilote_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE profil_pilote DROP CONSTRAINT FK_1BCDDD8FF510AAE9');
        $this->addSql('DROP TABLE profil_pilote');
    }
}
