<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251015034438 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE status (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE client ADD decimal_round INT DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD main_packaging_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE item ADD main_packaging_id INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE status');
        $this->addSql('ALTER TABLE client DROP decimal_round');
        $this->addSql('ALTER TABLE item DROP main_packaging_name');
        $this->addSql('ALTER TABLE item DROP main_packaging_id');
    }
}
