<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250819062953 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pilot_qualification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_obtention TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, profil_id INT DEFAULT NULL, qualification_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A9811BEE275ED078 ON pilot_qualification (profil_id)');
        $this->addSql('CREATE INDEX IDX_A9811BEE1A75EE38 ON pilot_qualification (qualification_id)');
        $this->addSql('ALTER TABLE pilot_qualification ADD CONSTRAINT FK_A9811BEE275ED078 FOREIGN KEY (profil_id) REFERENCES profil_pilote (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pilot_qualification ADD CONSTRAINT FK_A9811BEE1A75EE38 FOREIGN KEY (qualification_id) REFERENCES qualification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE profil_pilote ADD birth_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE profil_pilote ADD total_flight_hours DOUBLE PRECISION DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE pilot_qualification DROP CONSTRAINT FK_A9811BEE275ED078');
        $this->addSql('ALTER TABLE pilot_qualification DROP CONSTRAINT FK_A9811BEE1A75EE38');
        $this->addSql('DROP TABLE pilot_qualification');
        $this->addSql('ALTER TABLE profil_pilote DROP birth_date');
        $this->addSql('ALTER TABLE profil_pilote DROP total_flight_hours');
    }
}
