<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250604150834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reference VARCHAR(100) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, date DATE DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, reservation_code VARCHAR(100) DEFAULT NULL, remarques TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE payment_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mode VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, payment_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B3EE4054C3A3BB ON payment_detail (payment_id)');
        $this->addSql('ALTER TABLE payment_detail ADD CONSTRAINT FK_B3EE4054C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD code VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation ADD payment_reference VARCHAR(100) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE payment_detail DROP CONSTRAINT FK_B3EE4054C3A3BB');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE payment_detail');
        $this->addSql('ALTER TABLE reservation DROP code');
        $this->addSql('ALTER TABLE reservation DROP payment_reference');
    }
}
