<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241116142728 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, quantite INT DEFAULT NULL, creneau TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, prix DOUBLE PRECISION DEFAULT NULL, circuit_id INT DEFAULT NULL, option_id INT DEFAULT NULL, pilote_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_42C84955CF2182C8 ON reservation (circuit_id)');
        $this->addSql('CREATE INDEX IDX_42C84955A7C41D6F ON reservation (option_id)');
        $this->addSql('CREATE INDEX IDX_42C84955F510AAE9 ON reservation (pilote_id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955CF2182C8 FOREIGN KEY (circuit_id) REFERENCES circuit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955F510AAE9 FOREIGN KEY (pilote_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955CF2182C8');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955A7C41D6F');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955F510AAE9');
        $this->addSql('DROP TABLE reservation');
    }
}
