<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250412063715 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cadeau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) DEFAULT NULL, beneficiaire VARCHAR(255) DEFAULT NULL, offreur VARCHAR(255) DEFAULT NULL, fin DATE DEFAULT NULL, payment_id VARCHAR(255) DEFAULT NULL, used BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE reservation ADD cadeau_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955D9D5ED84 FOREIGN KEY (cadeau_id) REFERENCES cadeau (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42C84955D9D5ED84 ON reservation (cadeau_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP TABLE cadeau');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955D9D5ED84');
        $this->addSql('DROP INDEX UNIQ_42C84955D9D5ED84');
        $this->addSql('ALTER TABLE reservation DROP cadeau_id');
    }
}
