<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250317194345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entretien (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE DEFAULT NULL, intervention TEXT DEFAULT NULL, horametre_intervention DOUBLE PRECISION DEFAULT NULL, horametre_next_intervention DOUBLE PRECISION DEFAULT NULL, aeronef_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2B58D6DABCB14BD8 ON entretien (aeronef_id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT FK_2B58D6DABCB14BD8 FOREIGN KEY (aeronef_id) REFERENCES aeronef (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE entretien DROP CONSTRAINT FK_2B58D6DABCB14BD8');
        $this->addSql('DROP TABLE entretien');
    }
}
