<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250304124102 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE aeronef (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, immatriculation VARCHAR(6) DEFAULT NULL, horametre DOUBLE PRECISION DEFAULT NULL, entretien DOUBLE PRECISION DEFAULT NULL, decimal BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE circuit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) DEFAULT NULL, code VARCHAR(10) DEFAULT NULL, prix DOUBLE PRECISION DEFAULT NULL, cout DOUBLE PRECISION DEFAULT NULL, duree TIME(0) WITHOUT TIME ZONE DEFAULT NULL, prix_fixe BOOLEAN DEFAULT NULL, avec_options BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(60) DEFAULT NULL, prix DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE passager (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) DEFAULT NULL, prenom VARCHAR(100) DEFAULT NULL, email VARCHAR(200) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(15) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, duree DOUBLE PRECISION DEFAULT NULL, horametre_depart DOUBLE PRECISION DEFAULT NULL, horametre_fin DOUBLE PRECISION DEFAULT NULL, turnover DOUBLE PRECISION DEFAULT NULL, aeronef_id INT DEFAULT NULL, pilote_id UUID DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_51C88FADBCB14BD8 ON prestation (aeronef_id)');
        $this->addSql('CREATE INDEX IDX_51C88FADF510AAE9 ON prestation (pilote_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, quantite INT DEFAULT NULL, prix DOUBLE PRECISION DEFAULT NULL, debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, color VARCHAR(60) DEFAULT NULL, statut VARCHAR(80) DEFAULT NULL, remarques TEXT DEFAULT NULL, circuit_id INT DEFAULT NULL, option_id INT DEFAULT NULL, pilote_id UUID DEFAULT NULL, avion_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_42C84955CF2182C8 ON reservation (circuit_id)');
        $this->addSql('CREATE INDEX IDX_42C84955A7C41D6F ON reservation (option_id)');
        $this->addSql('CREATE INDEX IDX_42C84955F510AAE9 ON reservation (pilote_id)');
        $this->addSql('CREATE INDEX IDX_42C8495580BBB841 ON reservation (avion_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE vol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT DEFAULT NULL, duree DOUBLE PRECISION DEFAULT NULL, prix DOUBLE PRECISION DEFAULT NULL, circuit_id INT DEFAULT NULL, prestation_id INT DEFAULT NULL, option_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_95C97EBCF2182C8 ON vol (circuit_id)');
        $this->addSql('CREATE INDEX IDX_95C97EB9E45C554 ON vol (prestation_id)');
        $this->addSql('CREATE INDEX IDX_95C97EBA7C41D6F ON vol (option_id)');
        $this->addSql('ALTER TABLE prestation ADD CONSTRAINT FK_51C88FADBCB14BD8 FOREIGN KEY (aeronef_id) REFERENCES aeronef (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE prestation ADD CONSTRAINT FK_51C88FADF510AAE9 FOREIGN KEY (pilote_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955CF2182C8 FOREIGN KEY (circuit_id) REFERENCES circuit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955F510AAE9 FOREIGN KEY (pilote_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495580BBB841 FOREIGN KEY (avion_id) REFERENCES aeronef (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vol ADD CONSTRAINT FK_95C97EBCF2182C8 FOREIGN KEY (circuit_id) REFERENCES circuit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vol ADD CONSTRAINT FK_95C97EB9E45C554 FOREIGN KEY (prestation_id) REFERENCES prestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE vol ADD CONSTRAINT FK_95C97EBA7C41D6F FOREIGN KEY (option_id) REFERENCES option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE prestation DROP CONSTRAINT FK_51C88FADBCB14BD8');
        $this->addSql('ALTER TABLE prestation DROP CONSTRAINT FK_51C88FADF510AAE9');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955CF2182C8');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955A7C41D6F');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955F510AAE9');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495580BBB841');
        $this->addSql('ALTER TABLE vol DROP CONSTRAINT FK_95C97EBCF2182C8');
        $this->addSql('ALTER TABLE vol DROP CONSTRAINT FK_95C97EB9E45C554');
        $this->addSql('ALTER TABLE vol DROP CONSTRAINT FK_95C97EBA7C41D6F');
        $this->addSql('DROP TABLE aeronef');
        $this->addSql('DROP TABLE circuit');
        $this->addSql('DROP TABLE option');
        $this->addSql('DROP TABLE nature');
        $this->addSql('DROP TABLE passager');
        $this->addSql('DROP TABLE prestation');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vol');
    }
}
