<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251013131029 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE achat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivery_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, supplier_id INT DEFAULT NULL, supplier VARCHAR(255) DEFAULT NULL, base_currency VARCHAR(6) DEFAULT NULL, target_currency VARCHAR(6) DEFAULT NULL, exchange_rate DOUBLE PRECISION DEFAULT NULL, total_ht DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT DEFAULT NULL, product VARCHAR(255) DEFAULT NULL, packaging_id INT DEFAULT NULL, packaging VARCHAR(255) DEFAULT NULL, category_id INT DEFAULT NULL, category VARCHAR(255) DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, incoming_unit_price DOUBLE PRECISION DEFAULT NULL, out_going_unit_price_ht DOUBLE PRECISION DEFAULT NULL, total_price_ht DOUBLE PRECISION DEFAULT NULL, approch_coeff DOUBLE PRECISION DEFAULT NULL, cost_price_ht DOUBLE PRECISION DEFAULT NULL, achat_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F1B251EFE95D117 ON item (achat_id)');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251EFE95D117 FOREIGN KEY (achat_id) REFERENCES achat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251EFE95D117');
        $this->addSql('DROP TABLE achat');
        $this->addSql('DROP TABLE item');
    }
}
