#!/usr/bin/env python3
"""
Script pour ouvrir directement le plan comptable dans Odoo
et afficher les instructions de vérification
"""
import webbrowser

print("=" * 80)
print("VÉRIFICATION DU PLAN COMPTABLE DANS ODOO")
print("=" * 80)
print()
print("Instance: https://ah-chou1.odoo.com/odoo")
print("Login: mathieu.loic.hoarau@gmail.com")
print()
print("Ouverture du navigateur sur Odoo...")
print()

# Ouvrir Odoo
webbrowser.open("https://ah-chou1.odoo.com/web")

print("✓ Navigateur ouvert!")
print()
print("=" * 80)
print("INSTRUCTIONS DE VÉRIFICATION")
print("=" * 80)
print()
print("📋 Suivez ces étapes dans Odoo:")
print()
print("1. Connectez-vous si nécessaire")
print()
print("2. Ouvrez le module 'Accounting' (Comptabilité)")
print()
print("3. Allez dans: Configuration → Chart of Accounts")
print()
print("4. Vérifiez le NOMBRE TOTAL de comptes")
print("   → Cherchez le compteur en bas de la liste")
print("   → Attendu: 390 comptes")
print()
print("5. Recherchez les COMPTES CLÉS suivants:")
print()
print("   Code      | Nom                  | Type       | Lettrage")
print("   " + "-" * 68)
print("   40100000  | Fournisseurs         | Payable    | ✓ OUI")
print("   41100000  | Clients              | Receivable | ✓ OUI")
print("   41600000  | Clients douteux      | Receivable | ✓ OUI")
print("   60710000  | Achats march exo     | Expense    | ✗ NON")
print("   70700000  | Ventes exo LS        | Income     | ✗ NON")
print("   10100000  | Capital              | Equity     | ✗ NON")
print()
print("6. Pour chaque compte:")
print("   - Tapez le CODE dans la barre de recherche")
print("   - Cliquez sur le compte pour voir les détails")
print("   - Vérifiez le Type et le Lettrage (Allow Reconciliation)")
print()
print("=" * 80)
print("CHECKLIST DÉTAILLÉE")
print("=" * 80)
print()
print("Un fichier checklist complet est disponible:")
print("  CHECKLIST_VERIFICATION_IMPORT.md")
print()
print("Vous pouvez l'imprimer ou le consulter pendant la vérification.")
print()
print("=" * 80)
print("CE QU'IL FAUT VÉRIFIER")
print("=" * 80)
print()
print("✓ Nombre total de comptes: ________ / 390 attendus")
print()
print("✓ Comptes clés trouvés:")
print("  [ ] 40100000 - Fournisseurs (Payable + Lettrage)")
print("  [ ] 41100000 - Clients (Receivable + Lettrage)")
print("  [ ] 41600000 - Clients douteux (Receivable + Lettrage)")
print("  [ ] 60710000 - Achats march exo (Expense)")
print("  [ ] 70700000 - Ventes exo LS (Income)")
print("  [ ] 10100000 - Capital (Equity)")
print()
print("✓ Screenshots pris:")
print("  [ ] Liste complète avec compteur")
print("  [ ] Détails des comptes clés")
print()
print("=" * 80)
print("RÉSULTAT ATTENDU")
print("=" * 80)
print()
print("Si tout est OK, vous devriez avoir:")
print()
print("  ✅ 390 comptes dans le plan comptable")
print("  ✅ Les 6 comptes clés trouvés")
print("  ✅ Les types de comptes corrects")
print("  ✅ Le lettrage activé pour Clients et Fournisseurs uniquement")
print()
print("=" * 80)
print()
print("💡 ASTUCE:")
print("   Utilisez la fonction de recherche d'Odoo (en haut de la liste)")
print("   pour trouver rapidement chaque compte par son code.")
print()
print("📸 N'oubliez pas de prendre des screenshots!")
print()
print("=" * 80)
print()
